stage: ${env.NEXT_PUBLIC_STAGE}
name: delete-me

domain:
  dev: dev.codattest.com
  prod: codattest.com

website:
  component: '@serverless/website'
  inputs:
    bucketName: codabool-please-delete-${domain.${stage}}
    code:
      src: ./out
      hook: npm run deploy