# stage: ${env.STAGE}
# name: ${env.REPO}

# staging-your-site-name:
#   component: '@sls-next/serverless-component@1.18.0'
#   inputs:
#     memory: 128
#     bucketRegion: us-east-1
#     bucketName: ${name}-${stage}
#     name:
#       defaultLambda: ${name}-${stage}-default
#       apiLambda: ${name}-${stage}-api
#     # domain: ['staging-your-site-name', 'a-domain']
#     # domain:
#     #   - "${stage}-test"
#     #   - codadash.com
#     publicDirectoryCache: false
#     useServerlessTraceTarget: true
#     build:
#       env:
#         MONGODB_URI: ${env.MONGODB_URI}
#         NEXT_PUBLIC_STAGE: ${env.STAGE}


stage: ${env.STAGE}
name: next-mon

staging-your-site-name:
  component: '@sls-next/serverless-component@1.18.0'
  inputs:
    memory: 128
    bucketRegion: us-east-1
    bucketName: ${name}-${stage}
    name: 
      defaultLambda: ${name}-${stage}-default
      apiLambda: ${name}-${stage}-api
    publicDirectoryCache: false
    useServerlessTraceTarget: true
    build:
      env:
        MONGODB_URI: ${env.MONGODB_URI}
        NEXT_PUBLIC_STAGE: ${env.STAGE}
