stage: ${env.STAGE}
staging-your-site-name:
  component: '@sls-next/serverless-component@1.18.0'
  inputs:
    memory: 128
    bucketRegion: us-east-1
    bucketName: codabool-stage-test-1
    name: 
      defaultLambda: 
        - "${stage}-"
        - defaut
      apiLambda:
        - "${stage}-"
        - api
    # domain: ['staging-your-site-name', 'a-domain']
    domain:
      - "${stage}-test"
      - codadash.com
    publicDirectoryCache: false
    build:
      env:
        MONGODB_URI: ${env.MONGODB_URI}
        TEST_ENV: ${env.TEST_ENV}
        STAGE: ${env.STAGE}